
import { GoogleGenAI, Modality } from "@google/genai";
import { StickerShape, StickerType } from '../types';

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result.split(',')[1]);
      } else {
        reject(new Error('Failed to read file as base64 string.'));
      }
    };
    reader.onerror = (error) => reject(error);
  });
};

const createPrompt = (shape: StickerShape, type: StickerType): string => {
  const shapeDescription = {
    [StickerShape.Round]: 'perfectly round',
    [StickerShape.Square]: 'perfectly square',
    [StickerShape.Rectangle]: 'rectangular with a standard 4:3 aspect ratio',
  }[shape];

  const typeDescription = {
    [StickerType.Vinyl]: 'a high-quality printed vinyl sticker with a subtle matte or semi-gloss finish. It should look flat and precisely die-cut.',
    [StickerType.Domed]: 'a high-quality domed (resinado) sticker. This means it should have a clear, glossy, 3D polyurethane resin dome on top, giving it visible depth and a shiny, tactile appearance. The edges should look smooth and beveled due to the clear resin coating.',
  }[type];

  return `You are an expert graphic designer specializing in sticker production. Your task is to convert the user-provided image into a production-ready preview for a sticker.

**CRITICAL INSTRUCTIONS:**
1.  **Analyze the Image:** The input is likely a photo of a logo, storefront, or an existing design. Identify the main subject matter.
2.  **Clean and Enhance:** If the image is a photo (e.g., a sign on a wall), correct any perspective distortion, remove the background completely, and enhance the colors to be vibrant for printing. The result must be a clean graphic on a transparent background.
3.  **PRESERVE CORE CONTENT:** This is the most important rule. You MUST NOT alter, redraw, modify, or change any text, logos, or original branding elements. The integrity of the client's design is paramount.
4.  **Apply Sticker Format:**
    *   **Shape:** The final sticker must be shaped to be ${shapeDescription}.
    *   **Type:** The sticker must visually represent ${typeDescription}.
5.  **Final Output:** Generate a single, high-resolution image of the sticker preview. The background of the generated image itself MUST be transparent to isolate the sticker object.`;
};


export const generateStickerPreview = async (
    imageFile: File,
    shape: StickerShape,
    type: StickerType
): Promise<string> => {
    // FIX: Removed API_KEY check to align with guidelines assuming it's always available.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const base64Data = await fileToBase64(imageFile);
    const mimeType = imageFile.type;
    const prompt = createPrompt(shape, type);

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64Data,
                        mimeType: mimeType,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error('No image was generated by the API.');
};
