import { GoogleGenAI, Modality } from "@google/genai";
import { StickerShape, StickerType, RectangleOrientation } from '../types';

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result.split(',')[1]);
      } else {
        reject(new Error('Failed to read file as base64 string.'));
      }
    };
    reader.onerror = (error) => reject(error);
  });
};

const createPrompt = (shape: StickerShape, type: StickerType, orientation: RectangleOrientation): string => {
  let shapeDescription: string;

  if (shape === StickerShape.Rectangle) {
    const orientationDesc = orientation === RectangleOrientation.Portrait 
      ? 'em orientação de retrato (mais alto do que largo) com uma proporção de 3:4' 
      : 'em orientação de paisagem (mais largo do que alto) com uma proporção de 4:3';
    shapeDescription = `retangular ${orientationDesc}`;
  } else {
    shapeDescription = {
      [StickerShape.Round]: 'perfeitamente redondo',
      [StickerShape.Square]: 'perfeitamente quadrado',
    }[shape];
  }

  const typeDescription = {
    [StickerType.Vinyl]: 'um adesivo de vinil impresso de alta qualidade com um acabamento sutil fosco ou semi-brilho. Deve parecer plano e com corte preciso.',
    [StickerType.Domed]: 'um adesivo resinado (alto relevo) de alta qualidade. Isso significa que deve ter uma cúpula de resina de poliuretano transparente e brilhante por cima, conferindo-lhe profundidade visível e uma aparência tátil e brilhante. As bordas devem parecer suaves e chanfradas devido ao revestimento de resina transparente.',
  }[type];

  return `Você é um designer gráfico especialista em produção de adesivos. Sua tarefa é converter a imagem fornecida pelo usuário em uma prévia pronta para produção de um adesivo.

**INSTRUÇÕES CRÍTICAS:**
1.  **Analisar a Imagem:** A entrada é provavelmente uma foto de um logotipo, fachada de loja ou um design existente. Identifique o assunto principal.
2.  **Limpar e Melhorar:** Se a imagem for uma foto (por exemplo, uma placa em uma parede), corrija qualquer distorção de perspectiva, remova o fundo original e realce as cores para que fiquem vibrantes para impressão. O resultado deve ser um gráfico limpo do adesivo.
3.  **PRESERVAR O CONTEÚDO PRINCIPAL:** Esta é a regra mais importante. Você NÃO DEVE alterar, redesenhar, modificar ou mudar nenhum texto, logotipo ou elementos de marca originais. A integridade do design do cliente é fundamental.
4.  **Aplicar Formato do Adesivo:**
    *   **Formato:** O adesivo final deve ter o formato ${shapeDescription}.
    *   **Tipo:** O adesivo deve representar visualmente ${typeDescription}.
5.  **Saída Final:** Gere uma única imagem de alta resolução da prévia do adesivo. A imagem final deve consistir em duas camadas distintas:
    *   **1. Camada de Fundo (Marca d'água):** O fundo NÃO deve ser branco sólido. Em vez disso, crie um padrão de marca d'água em mosaico. O texto "GID Adesivos - 2025 © / Todos os Direitos Reservados" deve ser repetido várias vezes em um tom de cinza claro e sutil para preencher toda a área de fundo da imagem. O padrão deve ser diagonal e repetido.
    *   **2. Camada do Adesivo:** A prévia do adesivo que você criar (limpa e no formato correto) deve ser colocada NA FRENTE desta camada de fundo com marca d'água. O adesivo em si não deve ter a marca d'água sobre ele. O resultado final é uma imagem onde o adesivo se destaca claramente sobre um fundo totalmente coberto pela marca d'água repetida.`;
};


export const generateStickerPreview = async (
    imageFile: File,
    shape: StickerShape,
    type: StickerType,
    orientation: RectangleOrientation
): Promise<string> => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const base64Data = await fileToBase64(imageFile);
    const mimeType = imageFile.type;
    const prompt = createPrompt(shape, type, orientation);

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64Data,
                        mimeType: mimeType,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error('No image was generated by the API.');
};
